CREATE TABLE `ecpayOrders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`merchantTradeNo` varchar(20) NOT NULL,
	`tradeNo` varchar(20),
	`fullName` varchar(255) NOT NULL,
	`gender` enum('male','female','other') NOT NULL,
	`phone` varchar(30) NOT NULL,
	`email` varchar(320),
	`taxId` varchar(20),
	`deliveryMethod` enum('home','711') NOT NULL,
	`address` text,
	`storeCode` varchar(255),
	`items` text NOT NULL,
	`totalAmount` decimal(10,2) NOT NULL,
	`shippingFee` decimal(10,2) NOT NULL DEFAULT '0',
	`note` text,
	`status` enum('pending','paid','failed','cancelled') NOT NULL DEFAULT 'pending',
	`rtnCode` int,
	`rtnMsg` varchar(200),
	`paymentDate` varchar(20),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ecpayOrders_id` PRIMARY KEY(`id`),
	CONSTRAINT `ecpayOrders_merchantTradeNo_unique` UNIQUE(`merchantTradeNo`)
);
